baseURL = "https://mattn.pages.dev/"
languageCode = "en-us"
title = "俺の塩"
theme = "hugo-theme-nix"
paginate = 5

[params]
  Name = "mattn"
  HeaderUsername = "mattn"
  HeaderHostname = "mattn.pages.dev"
  About = "塩漬けの日々"
  ProfilePicture = "https://mattn.kaoriya.net/images/logo.png"

[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"

